### ISSUE TITLE
mtl 2.2.x

### ISSUE THREAD

**Issue by peti** [tatac1/amqp-conduit#1]
Do you realize that the dependency on mtl 2.2.x means that GHC 7.8.x cannot reliably compile this module? The compiler ships transformers 0.3.x as a core library, which cannot be replaced, and mtl 2.2.x requires transformers 0.4.x.

**Comment by tatac1** [comment]
I installed GHC version 7.8.3 on OS X Yosemite and Linux Arch, and I can compile amqp-conduit-0.1.0.0 with mtl-2.2.1 and transformers-0.4.2.0 on cabal-sandbox.

**Comment by peti** [comment]
Sure you can, but you cannot link any library that directly or indirectly depends on the core version of transformers. Try adding `doctest` as a dependency, for example, and check what `cabal configure` will tell you.

**Comment by tatac1** [comment]
You mean down grading mtl 2.1.\*  for transformers 0.3.x? if so I will look into this

**Comment by peti** [comment]
If your package could support mtl 2.1.x, then that would be great.

**Comment by tatac1** [comment]
the package v0.1.0.1 has been downgraded for GHC 7.8.x.

**Comment by peti** [comment]
Very cool, thank you!
